### ISSUE TITLE
User generation script

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#5]
- [ ] User needs to be given skills (i.e. 3 skills)
- [ ] Generate usernames and passwords
- [ ] Must be assigned a treatment and a group (i.e., funder, worker, researcher) within the treatment (i.e., no-metrics, health-metrics, market-metrics, both-metrics)
- [ ] Show appropriate dashboard for each group

**Comment by vinodahujauno** [comment]
@GeorgLink user generation script done. Please review at
https://github.com/vinodahujauno/bugmark_simulation/blob/master/exercise/simulation/script/user_gen_scr

**Comment by GeorgLink** [comment]
Looks good. Can you please make the following changes?

- [ ] Read the following from a settings file:
  * Number of users to generate and specific details on which groups/treatment combination they belong to
  * Starting balance for the different groups
  * Which skills are available
  * How many skills does a user get
- [ ] Do not randomize the group/treatment combinations, but generate exactly the numbers described in the settings file
- [ ] Set balances as described in the settings file.

**Comment by vinodahujauno** [comment]
@GeorgLink which setting file you are talking about. can you point out that file so that I can look at it "Read the following from a settings file: (lines 30-32)"

**Comment by vinodahujauno** [comment]
@GeorgLink as per your suggestion I have added section "Modify your input for users to be generated"

Please review and guide.

**Comment by GeorgLink** [comment]
The lines were referring to the script. You would have to create the settings file. The settings should be in a dedicated file, and not require changing the script. 
The settings file can be located in the same folder as the script.

I'm not set on a particular format, but this is what a YAML settings file might look like:

```yaml
---
create_users:
  - treatment: "no-metrics"
    group: "funder"
    budget: 100000
    number_of_new_users: 2
  - treatment: no-metrics
    group: "worker"
    budget: 100
    number_of_new_users: 10
  - treatment: "health-metrics"
    group: "funder"
    budget: 100000
    number_of_new_users: 2
  - treatment: "health-metrics"
    group: "worker"
    budget: 100
    number_of_new_users: 10
  - treatment: "market-metrics"
    group: "funder"
    budget: 100000
    number_of_new_users: 2
  - treatment: "market-metrics"
    group: "worker"
    budget: 100
    number_of_new_users: 10
  - treatment: "both-metrics"
    group: "funder"
    budget: 100000
    number_of_new_users: 2
  - treatment: "both-metrics"
    group: "funder"
    budget: 100
    number_of_new_users: 10
  - treatment: "admin"
    group: ""
    budget: 10000000
    number_of_new_users: 1
```
